name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libffi-dev \
          libssl-dev \
          zip \
          unzip \
          build-essential \
          libltdl-dev \
          autotools-dev \
          automake \
          pkg-config \
          git
          
    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
          
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Install Python build dependencies
      run: |
        pip install --upgrade pip wheel 'setuptools<68'
        pip install buildozer==1.5.0 cython==0.29.36 virtualenv python-for-android==2024.06.02
        
    - name: Verify buildozer.spec
      run: |
        echo "Checking buildozer.spec configuration..."
        cat buildozer.spec
        
    - name: Initialize buildozer
      run: |
        buildozer android clean
        
    - name: Build APK
      run: |
        buildozer -v android debug
        
    - name: List build output
      run: |
        echo "Build completed. Listing bin directory:"
        ls -la bin/ || echo "No bin directory found"
        find . -name "*.apk" -type f 2>/dev/null || echo "No APK files found"
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: escola-segura-apk
        path: bin/*.apk
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: |
          .buildozer/
          buildozer.log
        retention-days: 7