name: Build Android APK

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          
      - name: Install Buildozer and Cython
        run: |
          pip install --user --upgrade buildozer cython==0.29.36
          
      - name: Set Java environment
        run: |
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          echo "JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64" >> $GITHUB_ENV
          
      - name: Clean build environment
        run: |
          rm -rf .buildozer
          
      - name: Build APK
        run: |
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          yes | buildozer android debug
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk